#
include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = nextspace-applications
VERSION = 0.92
SUBPROJECTS = \
	Login \
	Workspace \
	Preferences \
	Terminal \
	TextEdit \
	TimeMon \
	Review \
	OpenUp \
        BatMon
    

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble

